### ISSUE TITLE
typing "i" crashes detEdit Figure 201

### ISSUE THREAD

**Issue by namariD** [ScrippsWhaleAcoustics/DetEdit#49]
While reviewing sessions using detEdit, if you accidentally hit the "i" key instead of "u" Figure 201 breaks and is unrecoverable (to the best of my knowledge). I have tried replacing the TPWS file and remade the LTSA1 file but kept the ID1 file and it still doesn't work. I have to continue with a new set of LTSA1/ID1/FP1/TP1 files.

Matlab error message in command window:
`Subscript indices must either be real positive integers or logicals.

Error in figure201 (line 23)
        set(hRLID,'Color',p.colorTab(dPARAMS.specIDs(iC2),:))

Error in boutMotion (line 254)
figure201

Error in keyAction (line 275)
boutMotion
 
Error while evaluating Figure KeyPressFcn.`

![image](https://user-images.githubusercontent.com/50114391/110704439-f3de4200-81c2-11eb-8038-81851383c7b0.png)

**Comment by kfrasier** [comment]
Hi, this is probably because some zeros got into the ID file accidentally somehow. We should figure out a catch for this. Meanwhile, try:

load(yourIDfile)
zID(zID(:,2)==0,:)=[];
save(yourIDfile,'zID','typeNames','-v7.3')

(Save a backup copy of your ID1 file somewhere just in case).

**Comment by namariD** [comment]
Hi, I have tried the solution provided and still have the issue. At first, I tried the code you sent, here is what I did:

`load('WAT_WC_01_disk02_BeakedWhale_ID1.mat')`
>> zID(zID(:,2)==0);
>> zID(zID(:,2)==0,:)=[];
>> save('WAT_WC_01_disk02_BeakedWhale_ID1.mat','zID','typeNames','-v7.3')
Error using save
Variable 'typeNames' not found.`

Then I used clear all and brought in the original file again and executed `unique(zID(:,2));`. Looks like using the key "i" puts imaginary numbers into the zID file?

(printout of the result of using unique)
0.00000000000000 + 1.00000000000000i
2.00000000000000 + 0.00000000000000i
4.00000000000000 + 0.00000000000000i
5.00000000000000 + 0.00000000000000i
6.00000000000000 + 0.00000000000000i
9.00000000000000 + 0.00000000000000i
10.0000000000000 + 0.00000000000000i

Would you know how to revert these complex values back to integers? I tried using `cast(zID(:,2),'int8')` and still end up with a complex int8:
0 + 1i
2 + 0i
4 + 0i
5 + 0i
6 + 0i
9 + 0i
10 + 0i

**Comment by kfrasier** [comment]
Ok, that's very interesting.

real() should convert them back to integers.

**Comment by namariD** [comment]
Hi,

That worked, here's what I did to fix the issue:

`load('WAT_WC_01_disk02_BeakedWhale_ID1.mat')
zID(:,2)=real(zID(:,2));
[M,I]= find(zID(:,2)==0);
zID(M,:)= [];
save('WAT_WC_01_disk02_BeakedWhale_ID1.mat','zID')`

Then I ran it through detEdit and was able to properly view that session. Thank you for the help, I really appreciate it! Glad it's an easy fix.
